'use strict'
const fs   = require('fs')
const path = require('path')
const os   = require('os')
const registry = require('./registry')

const tm = () => require('../tabManager')

// ── generateReport ───────────────────────────────────────────────────────────

registry.register({
  name: 'generateReport',
  description: 'Generate a formatted markdown report and save it to the Desktop. Returns the saved file path.',
  input_schema: {
    type: 'object',
    properties: {
      title:    { type: 'string', description: 'Report title' },
      content:  { type: 'string', description: 'Full report body in markdown format' },
      filename: { type: 'string', description: 'Output filename without extension. Defaults to the title.' },
    },
    required: ['title', 'content'],
  },
  async execute({ title, content, filename } = {}) {
    try {
      const base = (filename || title || 'report')
        .replace(/[^a-z0-9 _\-]/gi, '').trim().replace(/\s+/g, '_').slice(0, 60) || 'report'
      const stamp = new Date().toISOString().slice(0, 10)
      const header = `# ${title}\n\n*Generated by Strawberry · ${stamp}*\n\n---\n\n`
      const outPath = path.join(os.homedir(), 'Desktop', `${base}_${stamp}.md`)
      fs.mkdirSync(path.dirname(outPath), { recursive: true })
      fs.writeFileSync(outPath, header + content, 'utf8')
      return `Report saved to: ${outPath}`
    } catch (e) {
      return `Error saving report: ${e.message}`
    }
  },
})

// ── exportPDF ────────────────────────────────────────────────────────────────

registry.register({
  name: 'exportPDF',
  description: 'Save the current browser page as a PDF file to the Desktop. Returns the file path.',
  input_schema: {
    type: 'object',
    properties: {
      filename: { type: 'string', description: 'Output filename without .pdf extension.' },
    },
    required: [],
  },
  async execute({ filename } = {}) {
    const tab = tm().getActiveTab()
    if (!tab || tab.type !== 'browser') return 'No browser tab active.'
    try {
      const buf  = await tab.view.webContents.printToPDF({ printBackground: true, pageSize: 'A4' })
      const base = (filename || tab.url || 'page')
        .replace(/https?:\/\//, '').replace(/[^a-z0-9]/gi, '_').slice(0, 60) || 'page'
      const stamp = new Date().toISOString().slice(0, 10)
      const outPath = path.join(os.homedir(), 'Desktop', `${base}_${stamp}.pdf`)
      fs.writeFileSync(outPath, buf)
      return `PDF saved to: ${outPath}`
    } catch (e) {
      return `Error exporting PDF: ${e.message}`
    }
  },
})
